[project]
name = "bytes_parser"
version = "2.2.0"
description = ""
requires-python = ">=3.11"
license = "MIT"
readme = "README.md"

dependencies=[
    "pandas",
    "loguru"
]

[tool.uv]
config-settings = { editable_mode = "compat" }


[tool.ruff.lint]
preview = true